name: Makefile CI

on: 
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout main repo
      uses: actions/checkout@v3
      with:
        repository: ${{ github.repository }}
        path: minishell

    - name: compile
      run: make -C ./minishell/ -DLOG_LEVEL=ERROR" all #CFLAGS+="-DGITHUB_ACTIONS

    - name: checkout test repo
      uses: actions/checkout@v3
      with:
        repository: Han2-Ro/42minishell-tests
        path: minishell/tests

    - name: test
      run: make -C ./minishell/tests #CFLAGS+="-DGITHUB_ACTIONS"
